/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoRouteImport } from './routes/go'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PractitionerProfileEditorRouteImport } from './routes/practitioner/profile-editor'
import { Route as NotifyMeUnsubscribeRouteImport } from './routes/notify-me/unsubscribe'
import { Route as NotifyMeConfirmRouteImport } from './routes/notify-me/confirm'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PShortIdSlugRouteImport } from './routes/p.$shortId.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiCronStaleAlertRouteImport } from './routes/api/cron/stale-alert'
import { Route as ApiCronReVerifyRouteImport } from './routes/api/cron/re-verify'
import { Route as ApiCronMonthlySummaryRouteImport } from './routes/api/cron/monthly-summary'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerProfileEditorRoute =
  PractitionerProfileEditorRouteImport.update({
    id: '/practitioner/profile-editor',
    path: '/practitioner/profile-editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const NotifyMeUnsubscribeRoute = NotifyMeUnsubscribeRouteImport.update({
  id: '/notify-me/unsubscribe',
  path: '/notify-me/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifyMeConfirmRoute = NotifyMeConfirmRouteImport.update({
  id: '/notify-me/confirm',
  path: '/notify-me/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PShortIdSlugRoute = PShortIdSlugRouteImport.update({
  id: '/p/$shortId/$slug',
  path: '/p/$shortId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronStaleAlertRoute = ApiCronStaleAlertRouteImport.update({
  id: '/api/cron/stale-alert',
  path: '/api/cron/stale-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronReVerifyRoute = ApiCronReVerifyRouteImport.update({
  id: '/api/cron/re-verify',
  path: '/api/cron/re-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMonthlySummaryRoute = ApiCronMonthlySummaryRouteImport.update({
  id: '/api/cron/monthly-summary',
  path: '/api/cron/monthly-summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/go': typeof GoRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/notify-me/confirm': typeof NotifyMeConfirmRoute
  '/notify-me/unsubscribe': typeof NotifyMeUnsubscribeRoute
  '/practitioner/profile-editor': typeof PractitionerProfileEditorRoute
  '/api/cron/monthly-summary': typeof ApiCronMonthlySummaryRoute
  '/api/cron/re-verify': typeof ApiCronReVerifyRoute
  '/api/cron/stale-alert': typeof ApiCronStaleAlertRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/p/$shortId/$slug': typeof PShortIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/go': typeof GoRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/notify-me/confirm': typeof NotifyMeConfirmRoute
  '/notify-me/unsubscribe': typeof NotifyMeUnsubscribeRoute
  '/practitioner/profile-editor': typeof PractitionerProfileEditorRoute
  '/api/cron/monthly-summary': typeof ApiCronMonthlySummaryRoute
  '/api/cron/re-verify': typeof ApiCronReVerifyRoute
  '/api/cron/stale-alert': typeof ApiCronStaleAlertRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/p/$shortId/$slug': typeof PShortIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/go': typeof GoRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/notify-me/confirm': typeof NotifyMeConfirmRoute
  '/notify-me/unsubscribe': typeof NotifyMeUnsubscribeRoute
  '/practitioner/profile-editor': typeof PractitionerProfileEditorRoute
  '/api/cron/monthly-summary': typeof ApiCronMonthlySummaryRoute
  '/api/cron/re-verify': typeof ApiCronReVerifyRoute
  '/api/cron/stale-alert': typeof ApiCronStaleAlertRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/p/$shortId/$slug': typeof PShortIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/go'
    | '/login'
    | '/search'
    | '/signup'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/notify-me/confirm'
    | '/notify-me/unsubscribe'
    | '/practitioner/profile-editor'
    | '/api/cron/monthly-summary'
    | '/api/cron/re-verify'
    | '/api/cron/stale-alert'
    | '/api/stripe/webhook'
    | '/p/$shortId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/go'
    | '/login'
    | '/search'
    | '/signup'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/notify-me/confirm'
    | '/notify-me/unsubscribe'
    | '/practitioner/profile-editor'
    | '/api/cron/monthly-summary'
    | '/api/cron/re-verify'
    | '/api/cron/stale-alert'
    | '/api/stripe/webhook'
    | '/p/$shortId/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/go'
    | '/login'
    | '/search'
    | '/signup'
    | '/auth/callback'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/notify-me/confirm'
    | '/notify-me/unsubscribe'
    | '/practitioner/profile-editor'
    | '/api/cron/monthly-summary'
    | '/api/cron/re-verify'
    | '/api/cron/stale-alert'
    | '/api/stripe/webhook'
    | '/p/$shortId/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GoRoute: typeof GoRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  NotifyMeConfirmRoute: typeof NotifyMeConfirmRoute
  NotifyMeUnsubscribeRoute: typeof NotifyMeUnsubscribeRoute
  PractitionerProfileEditorRoute: typeof PractitionerProfileEditorRoute
  ApiCronMonthlySummaryRoute: typeof ApiCronMonthlySummaryRoute
  ApiCronReVerifyRoute: typeof ApiCronReVerifyRoute
  ApiCronStaleAlertRoute: typeof ApiCronStaleAlertRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  PShortIdSlugRoute: typeof PShortIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/profile-editor': {
      id: '/practitioner/profile-editor'
      path: '/practitioner/profile-editor'
      fullPath: '/practitioner/profile-editor'
      preLoaderRoute: typeof PractitionerProfileEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify-me/unsubscribe': {
      id: '/notify-me/unsubscribe'
      path: '/notify-me/unsubscribe'
      fullPath: '/notify-me/unsubscribe'
      preLoaderRoute: typeof NotifyMeUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notify-me/confirm': {
      id: '/notify-me/confirm'
      path: '/notify-me/confirm'
      fullPath: '/notify-me/confirm'
      preLoaderRoute: typeof NotifyMeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shortId/$slug': {
      id: '/p/$shortId/$slug'
      path: '/p/$shortId/$slug'
      fullPath: '/p/$shortId/$slug'
      preLoaderRoute: typeof PShortIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/stale-alert': {
      id: '/api/cron/stale-alert'
      path: '/api/cron/stale-alert'
      fullPath: '/api/cron/stale-alert'
      preLoaderRoute: typeof ApiCronStaleAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/re-verify': {
      id: '/api/cron/re-verify'
      path: '/api/cron/re-verify'
      fullPath: '/api/cron/re-verify'
      preLoaderRoute: typeof ApiCronReVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/monthly-summary': {
      id: '/api/cron/monthly-summary'
      path: '/api/cron/monthly-summary'
      fullPath: '/api/cron/monthly-summary'
      preLoaderRoute: typeof ApiCronMonthlySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GoRoute: GoRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  NotifyMeConfirmRoute: NotifyMeConfirmRoute,
  NotifyMeUnsubscribeRoute: NotifyMeUnsubscribeRoute,
  PractitionerProfileEditorRoute: PractitionerProfileEditorRoute,
  ApiCronMonthlySummaryRoute: ApiCronMonthlySummaryRoute,
  ApiCronReVerifyRoute: ApiCronReVerifyRoute,
  ApiCronStaleAlertRoute: ApiCronStaleAlertRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  PShortIdSlugRoute: PShortIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
