/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PractitionerProfileEditorRouteImport } from './routes/practitioner/profile-editor'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'
import { Route as PShortIdSlugRouteImport } from './routes/p.$shortId.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerProfileEditorRoute =
  PractitionerProfileEditorRouteImport.update({
    id: '/practitioner/profile-editor',
    path: '/practitioner/profile-editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PShortIdSlugRoute = PShortIdSlugRouteImport.update({
  id: '/p/$shortId/$slug',
  path: '/p/$shortId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/practitioner/profile-editor': typeof PractitionerProfileEditorRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/p/$shortId/$slug': typeof PShortIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/practitioner/profile-editor': typeof PractitionerProfileEditorRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/p/$shortId/$slug': typeof PShortIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/practitioner/profile-editor': typeof PractitionerProfileEditorRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/p/$shortId/$slug': typeof PShortIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/signup'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/practitioner/profile-editor'
    | '/api/stripe/webhook'
    | '/p/$shortId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/signup'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/practitioner/profile-editor'
    | '/api/stripe/webhook'
    | '/p/$shortId/$slug'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/signup'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/practitioner/profile-editor'
    | '/api/stripe/webhook'
    | '/p/$shortId/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  PractitionerProfileEditorRoute: typeof PractitionerProfileEditorRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  PShortIdSlugRoute: typeof PShortIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner/profile-editor': {
      id: '/practitioner/profile-editor'
      path: '/practitioner/profile-editor'
      fullPath: '/practitioner/profile-editor'
      preLoaderRoute: typeof PractitionerProfileEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shortId/$slug': {
      id: '/p/$shortId/$slug'
      path: '/p/$shortId/$slug'
      fullPath: '/p/$shortId/$slug'
      preLoaderRoute: typeof PShortIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  PractitionerProfileEditorRoute: PractitionerProfileEditorRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  PShortIdSlugRoute: PShortIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
